### PR TITLE
adds ability to pass custom header to requests

### PR DESCRIPTION
**Pull request by bauerjon**
my editor made a ton of noise, but this is what i added to every api method

```
header_params = opts.fetch(:headers, {})
```

@EndangeredMassa we are doing this so that we can pass an idempotency key to certain requests https://docsv2.dwolla.com/#idempotency-key

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
In the future, it would be great if whitespace changes could be in their own commit. No worries, though.

👍

**Comment by trek** [comment]
Is there a way to temporarily disable the whitespace changes? We regularly rebase off of https://github.com/Dwolla/dwolla-swagger-ruby and since their code is autogenned, it the whitespace changes won't exist.

**Comment by bauerjon** [comment]
no problemo. fixed!

**Comment by EndangeredMassa** [comment]
👍

**Pull request merged**
